### ISSUE TITLE
Too many hard links?

### ISSUE THREAD

**Issue by wyang007** [ic-hep/uncvmfs#2]
I am using uncvmfs 0.5 to unpack /cvmfs/altas.cern.ch. I was able to dump the tree to a local xfs file system. One of the files, /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/sw-mgr/v0.252.0/.alrb/tag has ~115K hard links. While xfs allows these many links, other file systems don't allow. So I can't move it to another place such as NERSC gpfs, etc.

I tried to dump it to a local ext4 filesystem. However, after creating 65000 hard links (max for ext4), uncvmfs places each of the rest 115k-65k=50k files on its own, instead of grouping them in a new hard  link. Is this possible?

I also wonder if it is really true that this file has ~115K links? There was one more example of this that I encountered.

**Comment by sfayer** [comment]
Hi,

The files are grouped by checksum (which is how the upstream CVMFS repo de-duplicates the files)... The most "popular" file in most of these repositories is a completely empty one which can appear many thousands of times in things like atlas.cern.ch and cms.cern.ch. It looks to me like the tag file is similar, it only contains two bytes and there are probably copies of it in lots of the subdirectories/packages.
(This was the main reason I didn't look at adding grouping above the first 65k links in the first place... There are very few files that have this many links and they're generally very small, so having lots of duplicates of them doesn't really "cost" very much)

I can have a look at adding some code to do grouping beyond the first batch if you think it would be advantageous to your situation?

Regards,
Simon

**Comment by wyang007** [comment]
Thanks for looking into this. I took a deeper look also and found similar explanation. At this point, I don't think it worth spending lots of energy to fix this issue.

**Comment by sfayer** [comment]
Thanks, I'll close the issue: Please reopen it/open a new ticket it if you ever do find that this is a problem.
